### ISSUE TITLE
狗哥的插件在移植到loon自定义app字幕时无法机翻

### ISSUE THREAD

**Issue by X1nyuZheng** [chengkongyiban/Loon#1]
选择netflix，disney都可以，但是配合快捷指令的General正确配置后，提示如下：
Log:
[JS exception]:TypeError: undefined is not an object (evaluating 'setting.type')

Surge下这个js是完美运行的，但是loon移植后无法翻译，请问大佬是否有同样的问题

**Comment by chengkongyiban** [comment]
我个人仅对YouTube字幕翻译有需求。在使用中无此问题。
