### ISSUE TITLE
在将QX重写转Loon时，脚本配置的argument最好用双引号包裹

### ISSUE THREAD

**Issue by Loon0x00** [chengkongyiban/Loon#2]
在将QX重写转Loon时，脚本配置的argument最好用双引号包裹
如下重写
`^https?:\/\/(?!d\.pcs).*(?<!map)\.baidu\.com url request-header (\r\n)User-Agent:.+iPhone.+(\r\n) request-header $1User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 13_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.1 Mobile/15E148 Safari/16C50 Quark/604.1 T7/10.3 SearchCraft/2.6.3 (Baidu; P1 8.0.0)$2`
最好转为这样：
`http-request ^https?:\/\/(?!d\.pcs).*(?<!map)\.baidu\.com script-path=https://raw.githubusercontent.com/xream/scripts/main/surge/modules/replace-header/index.js, tag=replaceHeader_5, argument="(\r\n)User-Agent:.+iPhone.+(\r\n)->$1User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 13_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.1 Mobile/15E148 Safari/16C50 Quark/604.1 T7/10.3 SearchCraft/2.6.3 (Baidu; P1 8.0.0)$2"`

该重写转化为Loon的配置时，因为Loon是以,分割解析脚本配置参数的，而参数中有","所以出现了解析argument异常的问题

**Comment by chengkongyiban** [comment]
谢谢，已修改。
